export const STRINGS = {
  home: {
    title: 'Hola',
    prompt: '¿Qué te gustaría hacer hoy?',
    newRecipe: 'Nueva receta',
    newRecipeSubtitle: 'Elige una receta según tu plan',
    continueRecipe: 'Continuar receta',
    continueRecipeSubtitle: 'Sigue con tu preparación actual',
    scanPlan: 'Escanear plan',
    scanPlanSubtitle: 'Carga tu dieta médica desde PDF o imagen',
  },
  recipes: {
    title: 'Recetas',
    subtitle: 'Selecciona una receta compatible con tu plan',
    yourRecipes: 'Tus recetas',
    yourRecipesSubtitle: 'Elegí una opción para hoy',
    emptyTitle: 'Escanea tu plan primero',
    emptyBody: 'Ve a Inicio y escanea tu dieta\npara ver recetas sugeridas',
  },
  scan: {
    title: 'Escanear plan',
    subtitle: 'Cargá tu dieta médica para obtener recetas personalizadas',
    pickPdf: 'Subir PDF',
    pickPdfSubtitle: 'Seleccioná un archivo PDF con tu plan nutricional',
    pickImage: 'Desde galería',
    pickImageSubtitle: 'Elegí una foto de tu dieta desde tu galería',
    takePhoto: 'Tomar foto',
    takePhotoSubtitle: 'Usá la cámara para capturar tu plan ahora',
    analyzing: 'Analizando dieta...',
    analyzingHint: 'Esto toma solo unos segundos',
  },
  preparation: {
    noRecipe: 'No hay receta seleccionada',
    connected: 'Conectado',
    scanning: 'Buscando...',
    disconnected: 'Sin conectar',
    step: 'Paso',
    target: 'Peso objetivo',
    inTolerance: '¡Peso correcto! Mantené...',
    objective: 'Objetivo',
    tolerance: 'Tolerancia',
    footer: 'La gramera pasará automáticamente al siguiente ingrediente',
  },
  validation: {
    loading: 'Cargando cámara...',
    permissionTitle: 'Permiso de cámara necesario',
    permissionBody: 'Necesitamos acceso a la cámara para validar tu plato preparado',
    grantPermission: 'Conceder permiso',
    back: 'Volver',
    captureHint: 'Tocá para capturar',
    title: 'Validar plato',
    processing: 'Analizando plato con IA...',
    processingSubtitle: 'Verificando ingredientes y porciones',
    success: '¡Plato validado!',
    successSubtitle: 'Excelente trabajo. Tu racha ha crecido.',
    seeProgress: 'Ver mi progreso',
    captureAria: 'Capturar foto',
  },
  profile: {
    title: 'Perfil',
    subtitle: 'Tu información y configuración',
    emptyTitle: 'Configuración próximamente',
    emptyBody: 'Tus datos, metas y preferencias\naparecerán aquí',
  },
  progress: {
    title: 'Progreso',
    subtitle: 'Tu evolución y racha actual',
    daysLabel: 'días de racha',
    emptyBody: 'Completá una receta para\nver más estadísticas',
  },
  errors: {
    bleUnavailableTitle: 'Bluetooth no disponible',
    bleUnavailableBody: 'El módulo BLE no está instalado en este dispositivo.',
    blePermissionTitle: 'Permisos requeridos',
    blePermissionBody: 'Necesitamos permisos de Bluetooth y ubicación para conectarte a la gramera.',
    bleOffTitle: 'Bluetooth apagado',
    bleOffBody: 'Por favor encendé el Bluetooth para continuar.',
  },
  notFound: {
    title: '404',
    body: 'La pantalla que buscás no existe.',
    action: 'Volver al inicio',
  },
  common: {
    cancel: 'Cancelar',
    retry: 'Reintentar',
  },
} as const;
